### ISSUE TITLE
`PrivateNetwork::legacy` is marked as required, though the api is returning `null`

### ISSUE THREAD

**Issue by naturalethic** [cycleplatform/api-spec#78]
I'm just getting started on testing out some live API's.

`CreateEnvironment` and `GetEnvironments` return a result of the type `Environment`.

`Environment` contains `PrivateNetwork` which contains `LegacyNetwork`.

In `PrivateNetwork` this field (`legacy`) is marked as required.  For the generator, any field that is required must have a value, and can never be null, unless it is also marked as `nullable`.  This field is not so marked.  Because it is a `$ref`, the spec does not appear to allow a `nullable` flag on the property.

I'm not certain what to do here.

I think you can place `nullable` on the referenced definition, but that seems odd as it would then apply nullability to the property of the containing type.

If simply removing this field from the required list is possible, that would fix the generator.

**Comment by mattoni** [comment]
This should be resolved, as of quite awhile ago. Let me know if there's still an issue.
